### ISSUE TITLE
Support NegotiateStream after it lights up in dotnet/corefx

### ISSUE THREAD

**Issue by iamjasonp** [dotnet/wcf#592]
Currently, System.Net.Security.NegotiateStream is stubbed out but not yet implemented. 

* [x] Windows implementation - dotnet/corefx#1844 
* [x] Linux implementation - dotnet/corefx#2483

**Comment by iamjasonp** [comment]
dotnet/corefx#5156 is the implementation port

**Comment by iamjasonp** [comment]
This was merged, and packages should be out. I'm updating the packages to test this.

**Comment by iamjasonp** [comment]
To do: 

* [x] Update project.json files to package version rc2-23712
* [ ] Update project.lock.json (they're to be deprecated, but while they exist we still have to update them
* [ ] Update the build scripts to have SUPPORTS_WINDOWSIDENTITY be defined
* [ ] Allow TransportSecurity tests with NegotiateStream to run

(Currently, build.cmd targets OSGroup = AnyOS, which prevents `SUPPORTS_WINDOWSIDENTITY` from being defined)

**Comment by iamjasonp** [comment]
We're lit up in Windows! We are waiting for this to be available on Linux.

**Comment by roncain** [comment]
Added label to indicate we are blocked in the Linux implementation by https://github.com/dotnet/corefx/issues/2483

**Comment by iamjasonp** [comment]
I'm privately building dotnet/corefx#5773 and seeing how far we can go.

**Comment by iamjasonp** [comment]
UPDATE: we are now at a point where we seem to be acquiring the Kerberos ticket, and we can see that WCF is doing the right things when calling NegotiateStream.AuthenticateAsClientAsync. However, the connection is still not yet established, and we're working through this one.

**Comment by iamjasonp** [comment]
This seems lit up, as tested with bits that I've manually built from the corresponding corefx NegotiateStream dev branch (https://github.com/iamjasonp/corefx/tree/devNegoUnix). 

Here are the details that need to be ironed out: 

- Testing will work from Linux->Windows only if: 
  - the Bridge is running as LOCAL SERVICE
  - client credentials are specified ahead of test time using `kinit` in Linux
  - or by specifying it explicitly on the factory 

```csharp 
factory = new ChannelFactory<IWcfService>(
    binding,
    new EndpointAddress(new Uri(Endpoints.Tcp_DefaultBinding_Address))
);


factory.Credentials.Windows.ClientCredential.Domain = "redmond";
factory.Credentials.Windows.ClientCredential.UserName = "someUser";
factory.Credentials.Windows.ClientCredential.Password = "somePassword";
```

What is going to be interesting is how we share these secrets around. 
If we don't want to pollute credentials, we may also have to do a `kdestroy` after each test. 

I'm testing ways out how to avoid starting the service as a LOCAL SERVICE, by explicitly specifying an SPN.

**Comment by iamjasonp** [comment]
Note that we can't explicitly specify an SpnEndpointIdentity yet (that's being looked at)

**Comment by iamjasonp** [comment]
https://github.com/dotnet/corefx/issues/6606 - tracks the issue where a process launched will fail if the process context is a user rather than a service.

**Comment by zhenlan** [comment]
Removed "blocked-by-partner" label. "tracking" label is already used to indicate the issue is dependent on another issue.

**Comment by iamjasonp** [comment]
Linux implementation has made it into corefx. We have done the due diligence to make sure it works, so this issue is completed. 

#851 tracks work on how to automate testing
#943 tracks looking at NTLM fallback
